function pgm_write(raster, pgm_filename)
  pgm_file = fopen(pgm_filename, 'wb');

  ## Print the header per mmpad_bad_pixel_map_creation.md
  fprintf(pgm_file, "P5\n# Generated by Octave\n%i %i\n255\n", size(raster)(2),size(raster)(1));

  ## Convert the raster to the mask format
  mod_raster = uint8(isnan(raster)');

  fwrite(pgm_file, mod_raster, 'uint8', 'b'); #Big-endian per PGM standard, although redundant since the pixels are one byte
  fclose(pgm_file);
  return
endfunction
